version: '3'

services:
  #POSTGRES DB
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_v3
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=user1
    networks:
      - my_network
  #DJANGO API
  djangogunicorn:
    volumes:
      - static:/static

    env_file: 
      - .env
    build:
      context: .
    ports: 
      - 8000:8000
    depends_on:
      - db
    networks:
      - my_network
  #PROXY FOR API docker internal network
  localnginx:
    build: ./nginxlocal
    volumes:
      - static:/static
    ports:
      - "81:80"
    networks:
      - my_network
  #NEXTJS CLIENT
  client:
    build: ./client
    ports:
      - 3000:3000

    networks:
      - my_network
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: canelosspa56@gmail.com
    volumes:
       - static:/static
       - media:/app/media
       - ./conf.d:/etc/nginx/user.conf.d:ro
       - letsencrypt:/etc/letsencrypt      
    #depends_on:
      #- djangogunicorn
    networks:
      - my_network
volumes:
  static:
  media:
  letsencrypt:

networks:
  my_network:
    driver: bridge
